# Generated by Django 3.2.7 on 2021-09-18 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bioma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_bioma', models.CharField(max_length=200, null=True, verbose_name='nom_bioma')),
                ('sigla_bioma', models.CharField(max_length=30, null=True, verbose_name='sigla_bioma')),
                ('des_altitudinal_bioma', models.CharField(max_length=30, null=True, verbose_name='des_altitudinal_bioma')),
                ('has_altitudinal_bioma', models.CharField(max_length=30, null=True, verbose_name='has_altitudinal_bioma')),
                ('remanencia', models.CharField(max_length=30, null=True, verbose_name='remanencia')),
                ('ext_bioma', models.CharField(max_length=30, null=True, verbose_name='ext_bioma')),
            ],
            options={
                'db_table': 'bioma',
            },
        ),
        migrations.CreateModel(
            name='estadoconservacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=30, null=True, verbose_name='categoria')),
                ('sigla', models.CharField(max_length=30, null=True, verbose_name='sigla')),
                ('descripcion', models.CharField(max_length=1000, null=True, verbose_name='descripcion')),
            ],
            options={
                'db_table': 'estadoconservacion',
            },
        ),
        migrations.CreateModel(
            name='fauna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_especie', models.CharField(max_length=200, null=True, verbose_name='nom_especie')),
                ('nom_cientifico', models.CharField(max_length=200, null=True, verbose_name='nom_cientifico')),
                ('nom_ingles', models.CharField(max_length=200, null=True, verbose_name='nom_ingles')),
                ('tipo', models.CharField(max_length=100, null=True, verbose_name='tipo')),
                ('rango_altitudinal', models.CharField(max_length=200, null=True, verbose_name='rango_altitudinal')),
                ('ubicacion', models.CharField(max_length=500, null=True, verbose_name='ubicacion')),
                ('descripcion', models.CharField(max_length=10000, null=True, verbose_name='descripcion')),
                ('autor', models.CharField(max_length=200, null=True, verbose_name='autor')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='albums/images/')),
                ('id_estado_conservacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto_app.estadoconservacion')),
            ],
            options={
                'db_table': 'fauna',
            },
        ),
        migrations.CreateModel(
            name='locacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_locacion', models.CharField(max_length=200, null=True, verbose_name='nom_locacion')),
                ('sigla_locacion', models.CharField(max_length=30, null=True, verbose_name='sigla_locacion')),
                ('alt_locacion', models.CharField(max_length=30, null=True, verbose_name='alt_locacion')),
                ('nombre_parroquia', models.CharField(max_length=30, null=True, verbose_name='nombre_parroquia')),
                ('nombre_canton', models.CharField(max_length=30, null=True, verbose_name='nombre_canton')),
                ('altitud', models.CharField(max_length=30, null=True, verbose_name='altitud')),
                ('longitud', models.CharField(max_length=30, null=True, verbose_name='longitud')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='albums/images/')),
                ('id_bioma', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto_app.bioma')),
            ],
            options={
                'db_table': 'locacion',
            },
        ),
        migrations.CreateModel(
            name='fauna_locacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_especie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto_app.fauna')),
                ('id_locacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto_app.locacion')),
            ],
            options={
                'db_table': 'fauna_locacion',
            },
        ),
        migrations.CreateModel(
            name='fauna_biomas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_bioma', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto_app.bioma')),
                ('id_especie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto_app.fauna')),
            ],
            options={
                'db_table': 'fauna_biomas',
            },
        ),
    ]
