# Generated by Django 3.2.7 on 2021-10-13 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fauna',
            name='imagen',
        ),
        migrations.CreateModel(
            name='imagen_fauna',
            fields=[
                ('id_ima', models.IntegerField(primary_key=True, serialize=False, verbose_name='id_fauna')),
                ('autor', models.CharField(max_length=200, null=True, verbose_name='autor')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='fauna')),
                ('id_especie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto_app.fauna')),
            ],
            options={
                'db_table': 'imagen_fauna',
            },
        ),
    ]
