# Generated by Django 3.2.7 on 2021-10-13 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_app', '0002_auto_20211013_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagen_fauna',
            name='id_ima',
        ),
        migrations.AddField(
            model_name='imagen_fauna',
            name='id_imagen',
            field=models.IntegerField(default=2, primary_key=True, serialize=False, verbose_name='id_imagen'),
            preserve_default=False,
        ),
    ]
